version: '3.3'

services:

    django:
        build: ./docker/python/
        image: my-django
        container_name: django
        tty: true
        working_dir: /src
        volumes:
            - ./project:/src
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000

    nginx:
        image: nginx:latest
        ports:
            - "80:80"

